const SCOPES = {
  SITE_ACCESS: 1,
  ADMIN: 2,
  READ_WRITE_REPORTS: 3,
  READ_REPORTS: 4,
  APPROVE_REPORTS: 5,
  UNLOCK_APPROVED_REPORTS: 6,
  READ_WRITE_TRAINING_REPORTS: 7,
  READ_TRAINING_REPORTS: 8,
  POC_TRAINING_REPORTS: 9,
}
export default SCOPES
