@startuml

title "TTA Hub Activity Reports"

actor User as TTAProvider
participant "TTA Hub\n frontend" as TTAHUBF
participant "TTA Hub\n backend" as TTAHUBB

group View: Activity Reports
    autonumber 1
    TTAProvider -> TTAHUBF : View landing page
    TTAProvider -> TTAHUBF : Navigate to Activity Reports
    TTAHUBF -> TTAHUBB : Request Page Data
    TTAHUBF <- TTAHUBB : Send display results
    TTAProvider -> TTAHUBF : [Optional] Filter results
    TTAHUBF -> TTAHUBB : send filter query
    TTAHUBF <- TTAHUBB : send display results
    TTAProvider -> TTAHUBF : [Optional] select spefic report
    TTAHUBF -> TTAHUBB : query specific report
    TTAHUBF <- TTAHUBB : send report results
end

group Edit: Edit Activity Reports
    autonumber 1
    TTAProvider -> TTAHUBF : Navigate to Activity Reports
    TTAProvider -> TTAHUBF : Select Report ID
    TTAHUBF -> TTAHUBB : Request selected report
    TTAHUBF <- TTAHUBB : Send Report Data
    TTAProvider -> TTAHUBF : Make changes as needed
    TTAProvider -> TTAHUBF : [Optional] Save Draft
    TTAHUBF -> TTAHUBB : Send draft report
    TTAHUBF <- TTAHUBB : Acknowledge Draft report saved
    TTAProvider -> TTAHUBF : [Optional] Submit for approval
    TTAHUBF -> TTAHUBB : Send completed report for approval
    TTAHUBF <- TTAHUBB : Accept Submission
    TTAHUBF -> TTAHUBF : Dispaly Activity Reports page
end

group Create: Create Activity Report
    autonumber 1
    TTAProvider -> TTAHUBF : Navigate to Activity Reports
    TTAProvider -> TTAHUBF : Click New Activity Report button
    TTAHUBF -> TTAHUBF : Display New Report Form
    TTAProvider -> TTAHUBF : Complete Activity Summary
    TTAProvider -> TTAHUBF : [Optional] Save As Draft
    TTAHUBF -> TTAHUBB : Send draft report
    TTAHUBF <- TTAHUBB : Acknowledge Draft report saved
    TTAProvider -> TTAHUBF : Save and Continue
    TTAHUBF -> TTAHUBF : Display Goals and Objectives
    TTAProvider -> TTAHUBF : Create/Select Goals and Objectives
    TTAProvider -> TTAHUBF : [Optional] Save As Draft
    TTAHUBF -> TTAHUBB : Send draft report
    TTAHUBF <- TTAHUBB : Acknowledge Draft report saved
    TTAProvider -> TTAHUBF : Save and Continue
    TTAHUBF -> TTAHUBF : Display Supporting Attachments 
    TTAProvider -> TTAHUBF : [Optional] Add supporting attachments
    TTAProvider -> TTAHUBF : [Optional] Save As Draft
    TTAHUBF -> TTAHUBB : Send draft report
    TTAHUBF <- TTAHUBB : Acknowledge Draft report saved
    TTAProvider -> TTAHUBF : Save and Continue
    TTAHUBF -> TTAHUBF : Display Next Steps
    TTAProvider -> TTAHUBF : Complete Next Steps
    TTAProvider -> TTAHUBF : [Optional] Save As Draft
    TTAHUBF -> TTAHUBB : Send draft report
    TTAHUBF <- TTAHUBB : Acknowledge Draft report saved
    TTAProvider -> TTAHUBF : Save and Continue
    TTAHUBF -> TTAHUBF : Display Review and Submit
    TTAProvider -> TTAHUBF : Complete Submit options
    TTAProvider -> TTAHUBF : [Optional] Save As Draft
    TTAHUBF -> TTAHUBB : Send draft report
    TTAHUBF <- TTAHUBB : Acknowledge Draft report saved
    TTAProvider -> TTAHUBF : Save and Submit
    TTAHUBF -> TTAHUBB : Send completed report for approval
    TTAHUBF <- TTAHUBB : Accept Submission
    TTAHUBF -> TTAHUBF : Dispaly Activity Reports page
end

@enduml