@startuml

title "TTA Hub Admin"

actor ADMIN as AD
participant "TTA Hub\n frontend" as FRONTEND
participant "TTA Hub\n backend" as BACKEND

group Administration: Admin Options
    autonumber 1
    AD -> FRONTEND : View landing page
    AD -> FRONTEND : Navigate to User\Admin
    FRONTEND <- BACKEND : Display Admin Page
    AD --> FRONTEND : Select Courses
    FRONTEND <-- BACKEND : Display Course page
    AD --> FRONTEND : Select Diag
    FRONTEND <-- BACKEND : Display Diag page
    AD --> FRONTEND : Select Goals
    FRONTEND <-- BACKEND : Display Goals page
    AD --> FRONTEND : Select Feature Flags
    FRONTEND <-- BACKEND : Display Feature Flags page
    AD --> FRONTEND : Select National Centers
    FRONTEND <-- BACKEND : Display National Centers page
    AD --> FRONTEND : Select Site Alerts
    FRONTEND <-- BACKEND : Display Site Alerts page
    AD --> FRONTEND : Select Training Reports
    FRONTEND <-- BACKEND : Display Training Reports page
    AD --> FRONTEND : Select Users
    FRONTEND <-- BACKEND : Display Users page
    AD --> FRONTEND : Select SS
    FRONTEND <-- BACKEND : Display Sheet List page
    AD --> FRONTEND : Select Redis info
    FRONTEND <-- BACKEND : Display Redis info page
end

@enduml