@startuml

title "TTA Hub Notifications"

actor TTAUSER as TU
participant "TTA Hub\n frontend" as FRONTEND
participant "TTA Hub\n backend" as BACKEND

group View: Notifications
    autonumber 1
    TU -> FRONTEND : View Landing Pages
    TU -> FRONTEND : Navigate to User\Notifications
    FRONTEND <- BACKEND : Display Notifications page
end

@enduml