@startuml

title "TTA QA Dashboard"

actor CREATOR as CR
actor COLLABORATOR as CL
actor REGIONALPOC as RPOC
participant "TTA Hub\n frontend" as FRONTEND
participant "TTA Hub\n backend" as BACKEND

group View : Quality Assurance Dashboard
' not yet implemented
end

@enduml