@startuml

title "TTA Regional Dashboard"

actor CREATOR as CR
actor COLLABORATOR as CL
actor REGIONALPOC as RPOC
participant "TTA Hub\n frontend" as FRONTEND
participant "TTA Hub\n backend" as BACKEND

group View : Regional Dashboard
    autonumber 1
    CR -> FRONTEND : View Landing Pages
    CR -> FRONTEND : Navigate to Regional Dashboard
    FRONTEND <- BACKEND: Display Regional Dashboard
    CR --> FRONTEND : Adjust Filters
    FRONTEND <-- BACKEND : Dipslay Regional Dashboard filter results
    CR --> FRONTEND : Click What does each status mean link
    FRONTEND <-- FRONTEND : Display help popup
    CR --> FRONTEND : Toggle Reason Table/Graph link
    FRONTEND <-- FRONTEND : Display selected view
    CR --> FRONTEND : Save Screenshot
    FRONTEND <-- FRONTEND : Cause browser to download screenshot
    CR --> FRONTEND : Toggle TTA Hours Table/Graph link
    FRONTEND <-- FRONTEND : Display selected view
    CR --> FRONTEND : Toggle Number of Reports High/Low
    FRONTEND <-- FRONTEND : Display selected sort
    CR --> FRONTEND : Number of Reports Save Screenshot
    FRONTEND <-- FRONTEND : Cause browser to download screenshot
    CR --> FRONTEND : Toggle Number of Reports Table/Graph link
    FRONTEND <-- FRONTEND : Display selected view
    CR --> FRONTEND : Export reports
    FRONTEND <-- FRONTEND : Cause browser to download csv reports
    CR --> FRONTEND : Click Report ID
    FRONTEND <-- BACKEND : Dispaly Activity Report page
    CR --> FRONTEND : Copy URL Link
    FRONTEND <-- FRONTEND : Copy URL link to clipboard
    CR --> FRONTEND : Print to PDF
    FRONTEND <-- FRONTEND : Cause Print dialog to open
end

@enduml