@startuml

title "TTA Resource Dashboard"

actor CREATOR as CR
actor COLLABORATOR as CL
actor REGIONALPOC as RPOC
participant "TTA Hub\n frontend" as FRONTEND
participant "TTA Hub\n backend" as BACKEND

group View : Resource Dashboard
    autonumber 1
    CR -> FRONTEND : View Landing Pages
    CR -> FRONTEND : Navigate to Resource Dashboard
    FRONTEND <- BACKEND: Display Resource Dashboard
    CR --> FRONTEND : Adjust Filters
    FRONTEND <-- BACKEND : Dipslay Resource Dashboard filter results
    CR --> FRONTEND : Export reports
    FRONTEND <-- FRONTEND : Cause browser to download csv reports
    CR --> FRONTEND : Select report ID link
    FRONTEND <-- BACKEND : Display TTA Activity Report
    CR --> FRONTEND : Copy URL Link
    FRONTEND <-- FRONTEND : Copy URL link to clipboard
    CR --> FRONTEND : Print to PDF
    FRONTEND <-- FRONTEND : Cause Print dialog to open
end


@enduml