@startuml

title "Recipient TTA Records"

actor CREATOR as CR
actor COLLABORATOR as CL
actor REGIONALPOC as RPOC
participant "TTA Hub\n frontend" as FRONTEND
participant "TTA Hub\n backend" as BACKEND

group View: Recipient Records
    autonumber 1
    CR -> FRONTEND : View Landing Pages
    CR -> FRONTEND : Navigate to Recipient TTA Records
    FRONTEND <- BACKEND: Display Recipient Records
end

group Search: Recipient Records
    autonumber 1
    CR -> FRONTEND : View Landing Pages
    CR -> FRONTEND : Navigate to Recipient TTA Records
    FRONTEND <- BACKEND: Display Recipient Records
    CR -> FRONTEND : Enter search criteria and Search
    FRONTEND <- BACKEND : Display Recipient Record results
    CR --> FRONTEND : Apply Filters
    FRONTEND <-- BACKEND : Display Recipient Record results
end

group View: Recipient Record
    autonumber 1
    CR -> FRONTEND : View Landing Pages
    CR -> FRONTEND : Navigate to Recipient TTA Records
    FRONTEND <- BACKEND: Display Recipient Records
    CR -> FRONTEND : Click Recipient Name link
    FRONTEND <- BACKEND : Display Selected Recipient Record
    CR --> FRONTEND : Click Grant Number
    FRONTEND <-- BACKEND : Extenernal - Navigate to OHS grant page
end

group View: RTTAPA tab
    autonumber 1
    CR -> FRONTEND : View Landing Pages
    CR -> FRONTEND : Navigate to Recipient TTA Records
    FRONTEND <- BACKEND: Display Recipient Records
    CR -> FRONTEND : Click Recipient Name link
    FRONTEND <- BACKEND : Display Selected Recipient Record
    CR -> FRONTEND : Click RTTAPA navigation tab
    FRONTEND <- BACKEND : Display RTTAPA page
    CR --> FRONTEND : Adjudt RTTAPA page filters
    FRONTEND <-- BACKEND : Display RTTAPA page filter results
    CR --> FRONTEND : Sort Goals and Objectives
    FRONTEND <-- BACKEND : Display RTTAPA page sort result
    CR --> FRONTEND : Adjust pagination
    FRONTEND <-- BACKEND : Display pagination results
    CR --> FRONTEND : Print and preview selected goals and objectives
    FRONTEND <-- BACKEND : Display printer view
    CR --> FRONTEND : Choose to Display/Hide objective
    FRONTEND <-- BACKEND : Display/Hide objective
    CR --> FRONTEND : Create New Goal
    FRONTEND <-- BACKEND : Display Recipient TTA Goal creation screen
    CR --> FRONTEND : Input data
    CR --> FRONTEND : Cancel
    CR --> FRONTEND : Save draft
    CR --> FRONTEND : Save and continue
    FRONTEND <-- BACKEND : Display RTTAPA page
end

group View: Communication tab
    autonumber 1
    CR -> FRONTEND : View Landing Pages
    CR -> FRONTEND : Navigate to Recipient TTA Records
    FRONTEND <- BACKEND: Display Recipient Records
    CR -> FRONTEND : Click Recipient Name link
    FRONTEND <- BACKEND : Display Selected Recipient Record
    CR -> FRONTEND : Click Communication navigation tab
    FRONTEND <- BACKEND : Display Communication page
    CR --> FRONTEND : Adjust Filters
    FRONTEND <-- BACKEND : Display Communication page results
    CR --> FRONTEND : Export Log
    FRONTEND <-- FRONTEND : Cause browser to download csv log
    CR --> FRONTEND : Select and click communication link
    FRONTEND <-- BACKEND : Display communication
    CR --> FRONTEND : Add Communication
    FRONTEND <-- BACKEND : Display Communication Log creation page
    CR --> FRONTEND : Enter required Data
    CR --> FRONTEND : Save and Continue
    CR --> FRONTEND : Save Log
    FRONTEND <-- BACKEND : Display Communication Log page
end

group View: TTA History tab
    autonumber 1
    CR -> FRONTEND : View Landing Pages
    CR -> FRONTEND : Navigate to Recipient TTA Records
    FRONTEND <- BACKEND: Display Recipient Records
    CR -> FRONTEND : Click Recipient Name link
    FRONTEND <- BACKEND : Display Selected Recipient Record
    CR -> FRONTEND : Click TTA History navigation tab
    FRONTEND <- BACKEND : Display TTA History page
    CR --> FRONTEND : Adjust Filters
    FRONTEND <-- BACKEND : Display TTA History page results
    CR --> FRONTEND : Toggle Reasons / Topics link
    FRONTEND <-- BACKEND : Display corresponding data
    CR --> FRONTEND : Toggle Table / Graph link
    FRONTEND <-- BACKEND : Display corresponding format
    CR --> FRONTEND : Export Reports
    FRONTEND <-- BACKEND : Cause browser to download csv reports
    CR --> FRONTEND : Click Report ID
    FRONTEND <-- BACKEND : Display Report
    CR --> FRONTEND : Copy URL Link
    FRONTEND <-- FRONTEND : Copy URL to clipboard
    CR --> FRONTEND : Print to PDF
    FRONTEND <-- FRONTEND : Cause Printer dialog to load
end

@enduml
