instances: 1
memory: 512M
disk_quota: 1GB

buildpack: "https://github.com/cloudfoundry/nodejs-buildpack"
command: "./automation/cf/scripts/idol.sh"

bound_services:
  - ttahub-db-backups # only needed to have an s3 for shared libraries to run correctly
  - ttahub-redis-prod # only needed to have an queue for shared libraries to run correctly
  - ttahub-process
