instances: 1
memory: 512M
disk_quota: 1GB

buildpack: "https://github.com/cloudfoundry/nodejs-buildpack"
command: "find /. -print | sed -e 's;[^/]*/;|____;g;s;____|; |;g'; ./automation/cf/scripts/idol.sh"

bound_services:
  - ttahub-process
