openapi: 3.0.2
tags:
  - name: status
info:
  version: 0.0.1
  title: TTADP
  contact:
    email: josh@adhocteam.us
servers:
  - url: http://localhost:8080
  - url: http://backend:8080
  - url: https://tta-smarthub-sandbox.app.cloud.gov
  - url: https://tta-smarthub-dev.app.cloud.gov
  - url: https://tta-smarthub-staging.app.cloud.gov
paths:
  $ref: "./paths/index.yaml"
components:
  schemas:
    activityReport:
      type: object
      description: >
        This object represents a report on an activity that a specialist has completed
        with 1 to many grants or non-grantees
      properties:
        id:
          type: number
        userId:
          type: number
          description: The id of the author of the report
        lastUpdatedById:
          type: number
          description: The id of the last user to update the report
        resourcesUsed:
          type: string
          description: A list of URLs used in the activity
        additionalNotes:
          type: string
          description: >
            Any additional info user's wish to convey about the report that is not
            captured elsewhere
        numberOfParticipants:
          type: number
          description: The number of people present at the activity
        deliveryMethod:
          type: string
          description: How the activity was connected, virtual vs in person
        duration:
          type: number
          description: How long the activity took to complete, in hours
        endDate:
          type: string
        startDate:
          type: string
        activityRecipientType:
          type: string
          description: The recipient type for the report, grant or non-grantee
        requester:
          type: string
          description: Who requested the TTA, grantee or regional office
        programTypes:
          type: array
          description: The type of grantee program, Head Start, Early Head Start, etc...
          items:
            type: string
        targetPopulations:
          type: array
          description: The target of the activity report
          items:
            type: string
        reason:
          type: array
          description: Why the activity was conducted
          items:
            type: string
        context:
          type: string
          description: Additional context an author can provide for a report
        participants:
          type: array
          description: The roles of the people attending the TTA
          items:
            type: string
        topics:
          type: array
          description: Topics covered during the TTA
          items:
            type: string
        pageState:
          type: object
          enum: ['Not Started', 'In progress', 'Completed']
          description: The state of each page of the form
          properties:
            1:
              type: string
            2:
              type: string
            3:
              type: string
            4:
              type: string
        status:
          type: string
          enum:
            - draft
            - submitted
            - approved
            - needs_action
          description: The current state of the report
        ttaType:
          type: array
          description: The type of the activity, Training or Technical Assistance (or both)
          items:
            type: string
    selectableUser:
      type: object
      description: >
        Users with only their id and name, ready to be placed in a select box on the frontend without
        further modification
      properties:
        id:
          type: number
        name:
          type: string
    activityRecipient:
      type: object
      description: A grant or non-grantee that can be added to an activity report
      properties:
        activityRecipientId:
          type: number
        name:
          type: string
    fileUpload:
      type: object
      properties:
        attachmentType:
          type: string
          description: "Type of attachment. Acceptable values are ATTACHMENT or RESOURCE"
        reportId:
          type: number
          description: "id of the Activity report the file is associated with"
        file:
          type: string
          format: binary
          description: "File to be uploaded"
      required:
      - attachmentType
      - reportId
      - File
    fileResponse:
      type: object
      description: ID of file created
      properties:
        id:
          type: number
    permission:
      type: object
      description: A combination of region, scope and user allowing that user to perform an action in a region
      properties:
        userId:
          type: number
        scopeId:
          type: number
        regionId:
          type: number
    user:
      type: object
      description: A TTA Smart Hub user
      properties:
        id:
          type: number
        name:
          type: string
        hsesUserId:
          type: number
        email:
          type: string
        phoneNumber:
          type: string
        homeRegionId:
          type: number
        title:
          type: string
        lastLogin:
          type: string
        permissions:
          type: array
          items:
            $ref: '#/components/schemas/permission'
