openapi: 3.0.2
tags:
  - name: status
info:
  version: 0.0.1
  title: TTADP
  contact:
    email: josh@adhocteam.us
servers:
  - url: http://localhost:8080
  - url: http://backend:8080
  - url: https://tta-smarthub-sandbox.app.cloud.gov
  - url: https://tta-smarthub-dev.app.cloud.gov
  - url: https://tta-smarthub-staging.app.cloud.gov
paths:
  $ref: "./paths/index.yaml"
components:
  schemas:
    approvingUser:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
    user:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        hsesUserId:
          type: number
        email:
          type: string
        phoneNumber:
          type: string
        homeRegionId:
          type: number
        title:
          type: string
        permissions:
          type: array
          items:
            $ref: '#/components/schemas/permission'
    permission:
      type: object
      properties:
        userId:
          type: number
        scopeId:
          type: number
        regionId:
          type: number
