openapi: 3.0.2
tags:
  - name: status
info:
  version: 0.0.1
  title: TTADP
  contact:
    email: josh@adhocteam.us
servers:
  - url: http://localhost:8080
  - url: http://backend:8080
  - url: https://tta-smarthub-sandbox.app.cloud.gov
  - url: https://tta-smarthub-dev.app.cloud.gov
  - url: https://tta-smarthub-staging.app.cloud.gov
paths:
  $ref: "./paths/index.yaml"
components:
  schemas:
    activityReport:
      type: object
      properties:
        id:
          type: number
        userId:
          type: number
        lastUpdatedById:
          type: number
        resourcesUsed:
          type: string
        additionalNotes:
          type: string
        numberOfParticipants:
          type: number
        deliveryMethod:
          type: string
        duration:
          type: number
        endDate:
          type: string
        startDate:
          type: string
        activityRecipientType:
          type: string
        requester:
          type: string
        programTypes:
          type: array
          items:
            type: string
        targetPopulations:
          type: array
          items:
            type: string
        reason:
          type: array
          items:
            type: string
        participants:
          type: array
          items:
            type: string
        topics:
          type: array
          items:
            type: string
        pageState:
          type: object
          properties:
            1:
              type: string
            2:
              type: string
            3:
              type: string
            4:
              type: string
        status:
          type: string
        ttaType:
          type: array
          items:
            type: string
    approvingUser:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
    activityRecipient:
      type: object
      properties:
        activityRecipientId:
          type: number
        name:
          type: string
    permission:
      type: object
      properties:
        userId:
          type: number
        scopeId:
          type: number
        regionId:
          type: number
    user:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        hsesUserId:
          type: number
        email:
          type: string
        phoneNumber:
          type: string
        homeRegionId:
          type: number
        title:
          type: string
        permissions:
          type: array
          items:
            $ref: '#/components/schemas/permission'
