version: "3.5"

networks:
  k6:
  grafana:

services:
  influxdb:
    image: influxdb:1.8
#    entrypoint: /bin/sh
#    user: root
    networks:
      - k6
      - grafana
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6

  grafana:
    image: grafana/grafana:8.5.21
#    entrypoint: /bin/sh
#    user: root
    networks:
      - grafana
    ports:
      - "3333:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ./tests/k6/dashboards:/var/lib/grafana/dashboards
      - ./tests/k6/grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./tests/k6/grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml

  k6:
    image: grafana/k6:latest-with-browser
    command: run /scripts/my-k6-script.ts
#    entrypoint: /bin/sh
#    user: root
    networks:
      - k6 
      - default
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./tests/k6/scripts:/scripts
