import {
  regionFilter,
  endDateFilter,
  startDateFilter,
  grantNumberFilter,
  programSpecialistFilter,
  programTypeFilter,
  reasonsFilter,
  recipientFilter,
  reportIdFilter,
  specialistRoleFilter,
  stateCodeFilter,
  targetPopulationsFilter,
  topicsFilter,
  otherEntitiesFilter,
} from '../../components/filter/activityReportFilters';

export const LANDING_BASE_FILTER_CONFIG = [
  endDateFilter,
  grantNumberFilter,
  otherEntitiesFilter,
  programSpecialistFilter,
  programTypeFilter,
  reasonsFilter,
  recipientFilter,
  reportIdFilter,
  specialistRoleFilter,
  startDateFilter,
  stateCodeFilter,
  targetPopulationsFilter,
  topicsFilter,
];

export const LANDING_FILTER_CONFIG_WITH_REGIONS = [
  endDateFilter,
  grantNumberFilter,
  otherEntitiesFilter,
  programSpecialistFilter,
  programTypeFilter,
  reasonsFilter,
  recipientFilter,
  regionFilter,
  reportIdFilter,
  specialistRoleFilter,
  startDateFilter,
  stateCodeFilter,
  targetPopulationsFilter,
  topicsFilter,
];
