env: prod
web_instances: 3
web_memory: 2GB
worker_instances: 1
worker_memory: 512M
LOG_LEVEL: info
AUTH_BASE: https://hses.ohs.acf.hhs.gov
# This env variable should go away soon in favor of TTA_SMART_HUB_URI
REDIRECT_URI_HOST: https://ttahub.ohs.acf.hhs.gov
TTA_SMART_HUB_URI: https://ttahub.ohs.acf.hhs.gov
CLAMAV_ENDPOINT: https://clamapi-ttahub-prod.apps.internal:9443
