env: prod
web_instances: 3
web_memory: 4GB
worker_instances: 2
worker_memory: 1GB
app_disk_quota: 4GB

app_name: tta-smarthub-prod
app_url: https://tta-smarthub-prod.app.cloud.gov/
cg_api: https://api.fr.cloud.gov
cg_org: hhs-acf-ohs-tta

LOG_LEVEL: info
AUTH_BASE: https://hses.ohs.acf.hhs.gov/oidc
# This env variable should go away soon in favor of TTA_SMART_HUB_URI
REDIRECT_URI_HOST: https://ttahub.ohs.acf.hhs.gov
TTA_SMART_HUB_URI: https://ttahub.ohs.acf.hhs.gov
OIDC_AUTH_METHOD: "private_key_jwt"
CLAMAV_ENDPOINT: https://clamapi-ttahub-prod.apps.internal:9443

SMARTSHEET_ENDPOINT: ""
SEND_NOTIFICATIONS: "true"
SUPPRESS_ERROR_LOGGING: "false"
FORCE_CRON: "false"

AUTH_CLIENT_ID: "${PROD_AUTH_CLIENT_ID}"
AUTH_CLIENT_SECRET: "${PROD_AUTH_CLIENT_SECRET}"
cg_username: "${CLOUDGOV_PROD_USERNAME}"
cg_password: "${CLOUDGOV_PROD_PASSWORD}"
cg_space: "${CLOUDGOV_PROD_SPACE}"

SESSION_SECRET: "${PROD_SESSION_SECRET}"
JWT_SECRET: "${PROD_JWT_SECRET}"
HSES_DATA_FILE_URL: "${PROD_HSES_DATA_FILE_URL}"
HSES_DATA_USERNAME: "${PROD_HSES_DATA_USERNAME}"
HSES_DATA_PASSWORD: "${PROD_HSES_DATA_PASSWORD}"
SMTP_HOST: "${SMTP_HOST}"
SMTP_PORT: "${SMTP_PORT}"
SMTP_HOST_TEST: "${SMTP_HOST_TEST}"
SMTP_PORT_TEST: "${SMTP_PORT_TEST}"
SMTP_SECURE: "${SMTP_SECURE}"
SMTP_IGNORE_TLS: "${SMTP_IGNORE_TLS}"
FROM_EMAIL_ADDRESS: "${FROM_EMAIL_ADDRESS}"
SMTP_USER: "${SMTP_USER}"
SMTP_PASSWORD: "${SMTP_PASSWORD}"
ITAMS_MD_HOST: "${ITAMS_MD_HOST}"
ITAMS_MD_PORT: "${ITAMS_MD_PORT}"
ITAMS_MD_USERNAME: "${ITAMS_MD_USERNAME}"
ITAMS_MD_PASSWORD: "${ITAMS_MD_PASSWORD}"
SMARTSHEET_ACCESS_TOKEN: "${SMARTSHEET_ACCESS_TOKEN}"

new_relic_app_id: "877570491"
new_relic_license: ${NEW_RELIC_LICENSE_KEY}

REACT_APP_GTM_ENABLED: ${PROD_GTM_ENABLED}
REACT_APP_GTM_ID: ${GLOBAL_GTM_ID}
REACT_APP_GTM_AUTH: ${PROD_GTM_AUTH}
REACT_APP_GTM_PREVIEW: ${PROD_GTM_PREVIEW}
REACT_APP_WEBSOCKET_URL: "wss://ttahub.ohs.acf.hhs.gov"
REACT_APP_INCLUDE_ACCESSIBILITY_CSS: "false"