env: prod
web_instances: 2
web_memory: 512M
worker_instances: 1
worker_memory: 512M
LOG_LEVEL: info
AUTH_BASE: TKTK
# This env variable should go away soon in favor of TTA_SMART_HUB_URI
REDIRECT_URI_HOST: https://ttahub.ohs.acf.hhs.gov
TTA_SMART_HUB_URI: https://ttahub.ohs.acf.hhs.gov
CLAMAV_ENDPOINT: http://clamapi-ttahub-prod.apps.internal:8080
