AUTH_BASE: https://uat.hsesinfo.org
AUTH_CLIENT_ID: ((AUTH_CLIENT_ID))
AUTH_CLIENT_SECRET: ((AUTH_CLIENT_SECRET))
env: prod
instances: 2
NODE_ENV: production
REDIRECT_URI_HOST: https://tta-smarthub-prod.app.cloud.gov
SESSION_SECRET: ((SESSION_SECRET))
