FROM python:3.9.21
COPY . .
COPY src/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip freeze > requirements.txt
ENV FLASK_ENV=development
WORKDIR /src
CMD ["flask", "run", "--host", "0.0.0.0", "--port", "5000", "--debug"]
