### no key
POST http://localhost:9100/compute
content-type: application/json

{ "recipient_id": "1", "alpha": 0.9 }




### bad key
POST http://localhost:9100/compute
content-type: application/json
X-API-KEY: badkey

{ "recipient_id": "1", "alpha": 0.9 }




### compute all similarities for a recipient
POST http://localhost:9100/compute
content-type: application/json
X-API-KEY: secret

{ "recipient_id": "3648", "alpha": 0.9 }




### given a text, compute similarities for this recipient
POST http://localhost:9100/compute
content-type: application/json
X-API-KEY: secret

{ "recipient_id": "3648", "text": "The leadership team will discuss and plan TTA needs for the 2022-23 program year.", "alpha": 0.9 }




### given a text_1 and text_2, compute the similarity between them
POST http://localhost:9100/compute
content-type: application/json
X-API-KEY: secret

{ "text_1": "hey world", "text_2": "hello world" }
