@startuml

' avoid problems with angled crows feet
  skinparam linetype ortho
  skinparam class {
    BorderColor #336A90
    BorderThickness 2
  }
  ' Classes

  class Files{
 * id : integer : <generated>
 * createdAt : timestamp with time zone
 * fileSize : integer
 * key : varchar(255)
 * originalFileName : varchar(255)
 * status : enum
 * updatedAt : timestamp with time zone
}
  class ImportDataFiles{
 * id : integer : <generated>
 * importFileId : integer : REFERENCES "ImportFiles".id
 * createdAt : timestamp with time zone
 * status : enum : 'IDENTIFIED'::"enum_ImportDataFiles_status"
 * updatedAt : timestamp with time zone
 fileInfo : jsonb
 hash : text
 recordCounts : jsonb
 schema : jsonb
}

class ImportFiles{
 * id : integer : <generated>
 fileId : integer : REFERENCES "Files".id
 * importId : integer : REFERENCES "Imports".id
 * createdAt : timestamp with time zone
 * downloadAttempts : integer : 0
 * processAttempts : integer : 0
 * status : enum : 'IDENTIFIED'::"enum_ImportFiles_status"
 * updatedAt : timestamp with time zone
 ftpFileInfo : jsonb
 hash : text
}

class Imports{
 * id : integer : <generated>
 * createdAt : timestamp with time zone
 * definitions : jsonb
 * enabled : boolean : false
 * ftpSettings : jsonb
 * name : text
 * schedule : text
 * updatedAt : timestamp with time zone
 fileMask : text
 path : text
 postProcessingActions : jsonb
}
ImportFiles "1" --[#black,dashed,thickness=2]--{  "n" ImportDataFiles : importFile, importDataFiles
Imports "1" --[#black,dashed,thickness=2]--{  "n" ImportFiles : import, importFiles
Files "1" --[#black,plain,thickness=2]-- "1" ImportFiles : importFile, file
@enduml