# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "activesupport", "~> 6.1"
gem "smartsheet", "~> 2.101"
gem "rake", "~> 13.0"
gem "faraday", "~> 1.3"
gem "faraday_middleware", "~> 1.0"
gem "faraday-cookie_jar"
