import { Op } from 'sequelize';
import { NOTIFICATION_TYPES } from '../../constants';

const VALID_TYPES = ['activityReport', 'collabReport', 'trainingReport', 'systemRelated', 'other'];

export const NOTIFICATION_TYPE_MAP: Record<string, string[]> = {
  activityReport: [
    NOTIFICATION_TYPES.ACTIVITY_REPORT_COLLABORATOR_ADDED,
    NOTIFICATION_TYPES.ACTIVITY_REPORT_NEEDS_ACTION,
    NOTIFICATION_TYPES.ACTIVITY_REPORT_SUBMITTED,
    NOTIFICATION_TYPES.ACTIVITY_REPORT_APPROVED,
    NOTIFICATION_TYPES.ACTIVITY_REPORT_RECIPIENT_REPORT_APPROVED,
    NOTIFICATION_TYPES.ACTIVITY_REPORT_RESUBMITTED,
  ],
  collabReport: [
    NOTIFICATION_TYPES.COLLAB_REPORT_COLLABORATOR_ADDED,
    NOTIFICATION_TYPES.COLLAB_REPORT_SUBMITTED,
    NOTIFICATION_TYPES.COLLAB_REPORT_RESUBMITTED,
    NOTIFICATION_TYPES.COLLAB_REPORT_NEEDS_ACTION,
    NOTIFICATION_TYPES.COLLAB_REPORT_APPROVED,
  ],
  trainingReport: [
    NOTIFICATION_TYPES.TRAINING_REPORT_POC_ADDED,
    NOTIFICATION_TYPES.TRAINING_REPORT_COLLABORATOR_ADDED,
    NOTIFICATION_TYPES.TRAINING_REPORT_SESSION_CREATED,
    NOTIFICATION_TYPES.TRAINING_REPORT_SESSION_SUBMITTED,
    NOTIFICATION_TYPES.TRAINING_REPORT_SESSION_NEEDS_ACTION,
    NOTIFICATION_TYPES.TRAINING_REPORT_SESSION_RESUBMITTED,
    NOTIFICATION_TYPES.TRAINING_REPORT_EVENT_COMPLETED,
    NOTIFICATION_TYPES.TRAINING_REPORT_TASK_DUE,
    NOTIFICATION_TYPES.TRAINING_REPORT_EVENT_IMPORTED,
    NOTIFICATION_TYPES.TRAINING_REPORT_EVENT_INFO_MISSING,
    NOTIFICATION_TYPES.TRAINING_REPORT_EVENT_INFO_PAST_DUE,
    NOTIFICATION_TYPES.TRAINING_REPORT_SESSION_INFO_MISSING,
    NOTIFICATION_TYPES.TRAINING_REPORT_SESSION_INFO_PAST_DUE,
    NOTIFICATION_TYPES.TRAINING_REPORT_NO_SESSIONS_CREATED,
    NOTIFICATION_TYPES.TRAINING_REPORT_NO_SESSIONS_PAST_DUE,
    NOTIFICATION_TYPES.TRAINING_REPORT_EVENT_NOT_COMPLETED,
    NOTIFICATION_TYPES.TRAINING_REPORT_EVENT_NOT_COMPLETED_PAST_DUE,
    NOTIFICATION_TYPES.TRAINING_REPORT_POC_ADDED_DIGEST,
    NOTIFICATION_TYPES.TRAINING_REPORT_COLLABORATOR_ADDED_DIGEST,
    NOTIFICATION_TYPES.TRAINING_REPORT_SESSION_SUBMITTED_DIGEST,
    NOTIFICATION_TYPES.TRAINING_REPORT_SESSION_NEEDS_ACTION_DIGEST,
    NOTIFICATION_TYPES.TRAINING_REPORT_EVENT_INFO_MISSING_DIGEST,
    NOTIFICATION_TYPES.TRAINING_REPORT_SESSION_INFO_MISSING_DIGEST,
    NOTIFICATION_TYPES.TRAINING_REPORT_NO_SESSIONS_CREATED_DIGEST,
    NOTIFICATION_TYPES.TRAINING_REPORT_EVENT_NOT_COMPLETED_DIGEST,
  ],
  systemRelated: [
    NOTIFICATION_TYPES.SYSTEM_PLANNED_OUTAGE,
    NOTIFICATION_TYPES.SYSTEM_UNPLANNED_OUTAGE,
  ],
  other: [
    NOTIFICATION_TYPES.COMMUNICATION_LOG_TTA_STAFF_ADDED,
    NOTIFICATION_TYPES.COMMUNICATION_LOG_RECIPIENT_IN_GROUP,
    NOTIFICATION_TYPES.COMMUNICATION_LOG_TTA_STAFF_ADDED_DIGEST,
    NOTIFICATION_TYPES.COMMUNICATION_LOG_RECIPIENT_IN_GROUP_DIGEST,
    NOTIFICATION_TYPES.MONITORING_GOAL_ADDED,
    NOTIFICATION_TYPES.MONITORING_DATA_RECEIVED,
    NOTIFICATION_TYPES.GROUP_CO_OWNER_ADDED,
    NOTIFICATION_TYPES.GROUP_SHARED,
  ],
};

function filterToNotificationTypes(types: string[]): string[] {
  const resolved = types
    .filter((t) => VALID_TYPES.includes(t))
    .flatMap((t) => NOTIFICATION_TYPE_MAP[t] ?? []);
  return Array.from(new Set(resolved));
}

export function withNotificationType(notificationTypes: string[]) {
  return {
    type: {
      [Op.in]: filterToNotificationTypes(notificationTypes),
    },
  };
}

export function withoutNotificationType(notificationTypes: string[]) {
  return {
    type: {
      [Op.notIn]: filterToNotificationTypes(notificationTypes),
    },
  };
}
