name: Pull Request Notifications (Test)

on:
  pull_request:
    branches:
      - main
    types: [ready_for_review]

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR body
        uses: actions/github-script@v7
        id: get-body
        with:
          result-encoding: string
          script: return context.payload.pull_request.body;

      - name: Notify Slack when a PR to main is opened (test)
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN_TEST }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo "${{ steps.get-body.outputs.result }}" > pr_body.md

          extract_section() {
            awk -v section="$1" '
              BEGIN {found=0}
              $0 ~ section {found=1; next}
              /^## / && found {exit}
              found {print}
            ' pr_body.md | head -c 400
          }

          DESC=$(extract_section "^## Description of change")
          TEST=$(extract_section "^## How to test")
          ISSUES=$(extract_section "^## Issue")

          PR_LINK="https://github.com/$GITHUB_REPOSITORY/pull/$PR_NUMBER"

          TEXT_MESSAGE=":rocket: *PR to main is now open!*\n>*Title:* $PR_TITLE\n>*Description:* $DESC\n>*How to test:* $TEST\n>*Issues:* $ISSUES\n$PR_LINK"

          curl -X POST -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
            -H 'Content-type: application/json;charset=utf-8' \
            --data "{
              \"channel\": \"github-test\",
              \"text\": \"$TEXT_MESSAGE\"
            }" https://slack.com/api/chat.postMessage
