name: Pull Request Notifications

on:
  pull_request:
    # branches:
    #   - production
    types: [opened, ready_for_review, closed, reopened]
  push:
    branches:
      - kw-github-slack

jobs:
  # notify_slack:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Notify slack when a PR to production is opened
  #     env:
  #       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  #     run: |
  #       PR_LINK="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/pull/${{ github.event.pull_request.number }}"
  #       curl -X POST -H 'Content-type: application/json' --data "{\"text\": \":rocket: A pull request (#${{ github.event.pull_request.number }}) to *production* is now open! <${PR_LINK}|Click here to view the PR>\"}" $SLACK_WEBHOOK_URL

  notify_slack_any_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Notify second Slack channel for any PR opened
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          if [ "$PR_NUMBER" != "" ]; then
            PR_LINK="https://github.com/$GITHUB_REPOSITORY/pull/$PR_NUMBER"
            TEXT_MESSAGE=":rocket: A production PR <$PR_LINK|$PR_NUMBER> is now open!"
          else
            TEXT_MESSAGE=":rocket: A new change was pushed to the production branch. Check the latest commits for more details."
          fi

          curl -X POST -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
          -H 'Content-type: application/json;charset=utf-8' \
          --data "{
            \"channel\": \"github-test\",
            \"text\": \"$TEXT_MESSAGE\"
          }" https://slack.com/api/chat.postMessage
