import { auditLogger } from '../logger';
import { sequelize } from '../models';

const tables = [
  'ZALActivityRecipients',
  'ZALActivityReportApprovers',
  'ZALActivityReportCollaborators',
  'ZALActivityReportFiles',
  'ZALActivityReportGoalFieldResponses',
  'ZALActivityReportGoalResources',
  'ZALActivityReportGoals',
  'ZALActivityReportObjectiveCitations',
  'ZALActivityReportObjectiveCourses',
  'ZALActivityReportObjectiveFiles',
  'ZALActivityReportObjectiveResources',
  'ZALActivityReportObjectiveTopics',
  'ZALActivityReportObjectives',
  'ZALActivityReportResources',
  'ZALActivityReports',
  'ZALCollabReportActivityStates',
  'ZALCollabReportApprovers',
  'ZALCollabReportDataUsed',
  'ZALCollabReportGoals',
  'ZALCollabReportReasons',
  'ZALCollabReportSpecialists',
  'ZALCollabReportSteps',
  'ZALCollabReports',
  'ZALCollaboratorRoles',
  'ZALCollaboratorTypes',
  'ZALCommunicationLogFiles',
  'ZALCommunicationLogRecipients',
  'ZALCommunicationLogs',
  'ZALCourses',
  'ZALEventReportPilotNationalCenterUsers',
  'ZALEventReportPilots',
  'ZALFiles',
  'ZALGoalCollaborators',
  'ZALGoalFieldResponses',
  'ZALGoalResources',
  'ZALGoalStatusChanges',
  'ZALGoalTemplateFieldPrompts',
  'ZALGoalTemplateObjectiveTemplates',
  'ZALGoalTemplateResources',
  'ZALGoalTemplates',
  'ZALGoals',
  'ZALGrantNumberLinks',
  'ZALGrantReplacementTypes',
  'ZALGrantReplacements',
  'ZALGrants',
  'ZALGroupCollaborators',
  'ZALGroupGrants',
  'ZALGroups',
  'ZALImportDataFiles',
  'ZALImportFiles',
  'ZALImports',
  'ZALMailerLogs',
  'ZALMaintenanceLogs',
  'ZALMonitoringClassSummaries',
  'ZALMonitoringFindingGrants',
  'ZALMonitoringFindingHistories',
  'ZALMonitoringFindingHistoryStatusLinks',
  'ZALMonitoringFindingHistoryStatuses',
  'ZALMonitoringFindingLinks',
  'ZALMonitoringFindingStandards',
  'ZALMonitoringFindingStatusLinks',
  'ZALMonitoringFindingStatuses',
  'ZALMonitoringFindings',
  'ZALMonitoringGranteeLinks',
  'ZALMonitoringReviewGrantees',
  'ZALMonitoringReviewLinks',
  'ZALMonitoringReviewStatusLinks',
  'ZALMonitoringReviewStatuses',
  'ZALMonitoringReviews',
  'ZALMonitoringStandardLinks',
  'ZALMonitoringStandards',
  'ZALNationalCenterUsers',
  'ZALNationalCenters',
  'ZALNextStepResources',
  'ZALNextSteps',
  'ZALObjectiveCollaborators',
  'ZALObjectiveTemplates',
  'ZALObjectives',
  'ZALOtherEntities',
  'ZALPermissions',
  'ZALProgramPersonnel',
  'ZALPrograms',
  'ZALRecipients',
  'ZALRegions',
  'ZALResources',
  'ZALRoleTopics',
  'ZALRoles',
  'ZALScopes',
  'ZALSessionReportPilotFiles',
  'ZALSessionReportPilotGoalTemplates',
  'ZALSessionReportPilotGrants',
  'ZALSessionReportPilotSupportingAttachments',
  'ZALSessionReportPilotTrainers',
  'ZALSessionReportPilots',
  'ZALSiteAlerts',
  'ZALTopics',
  'ZALUserRoles',
  'ZALUserSettingOverrides',
  'ZALUserSettings',
  'ZALUserValidationStatus',
  'ZALUsers',
  'ZALValidFor',
  'ZALZADescriptor',
  'ZALZAFilter',
];

async function logOldRecordsCount() {
  try {
    tables.forEach(async (table) => {
      const [results] = await sequelize.query(`SELECT COUNT(*) AS count FROM "${table}" WHERE "createdAt" < NOW() - INTERVAL '90 days';`);
      const count = results[0]?.count || 0;
      auditLogger.info(`Table: ${table}, Records older than 90 days: ${count}`);
    });
  } catch (error) {
    auditLogger.error(`Error logging old records count: ${error.message}`);
  }
}

logOldRecordsCount();
